flaskdb/service/forms.py
"""
A Sample Web-DB Application for DB-DESIGN lecture
Copyright (C) 2022 Yasuhiro Hayashi
"""
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, PasswordField, SubmitField
from wtforms.validators import DataRequired, length
from flaskdb.widgets import ButtonField

class LoginForm(FlaskForm):
    username = StringField(
        "User Name",
        validators = [
            DataRequired(message="User Name is required."),
            length(max=64, message="User Name should be input within 64 characters."),
        ],
    )
    password = PasswordField(
        "Password",
        validators = [
            DataRequired(message="Password is required."),
        ],
    )
    cancel = ButtonField("Cancel")
    submit = SubmitField("Login")

    def copy_from(self, user):
        self.username.data = user.username
        self.password.data = user.password

    def copy_to(self, user):
        user.username = self.username.data
        user.password = self.password.data

class AddItemForm(FlaskForm):
    itemname = StringField(
        "Item Name",
        validators = [
            DataRequired(message="Item Name is required."),
        ],
    )
    price = IntegerField(
        "Price",
        validators = [
            DataRequired(message="Price is required."),
        ],
    )
    cancel = ButtonField("Cencel")
    submit = SubmitField("Submit")

    def copy_from(self, item):
        self.itemname.data = item.itemname
        self.price.data = item.price

    def copy_to(self, item):
        item.itemname = self.itemname.data
        item.price = self.price.data

class SearchItemForm(FlaskForm):
    itemname = StringField(
        "Item Name",
        validators = [
            DataRequired(message="Item Name is required."),
        ],
    )
    cancel = ButtonField("Cencel")
    submit = SubmitField("Submit")

    def copy_from(self, item):
        self.itemname.data = item.itemname

    def copy_to(self, item):
        item.itemname = self.itemname.data

flaskdb/__init__.py
from flask import Flask
apps = Flask(__name__, static_folder="view/static", template_folder="view/templates")
apps.config.from_object("flaskdb.config")

from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy(apps)

from flaskdb.repository.dataaccess import DataAccess
import flaskdb.var as v
da = DataAccess(v.HOSTNAME, v.PORT, v.DBNAME, v.USERNAME, v.PASSWORD)

from flask_wtf.csrf import CSRFProtect
csrf = CSRFProtect()
csrf.init_app(apps)

from flask_bootstrap import Bootstrap
bs = Bootstrap(apps)


from flask_easymde import EasyMDE
from flaskext.markdown import Markdown
apps.config["EasyMDE_JS_IIFE"] = True
apps.config["EasyMDE_USE_CDN"] = True
EasyMDE(apps)
Markdown(apps, extensions=["nl2br", "fenced_code"])

from flaskdb.controller.views import app
from flaskdb.controller.auth import auth_module
from flaskdb.controller.memo import memo_module
from flaskdb.controller.share import share_module

apps.register_blueprint(app)
apps.register_blueprint(auth_module)
apps.register_blueprint(memo_module)
apps.register_blueprint(share_module)

flaskdb/controller/auth.py
from flask import Blueprint, request, session, render_template, redirect, flash, url_for
from flaskdb import apps, db, da
import datetime
from flaskdb.model.userModel import User
from flaskdb.controller.form.LoginForm import LoginForm
from flaskdb.service.mainService import create_private_folder

auth_module = Blueprint("auth", __name__)

@auth_module.route("/now", methods=["GET", "POST"])
def now():
    return str(datetime.datetime.now())

@auth_module.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data, password=form.password.data).first()

        if user is None or user.password != form.password.data:
            flash("ユーザー名あるいはパスワードが違います。", "danger")
            return redirect(url_for("auth.login"))

        session["username"] = user.username
        create_private_folder(session["username"])
        return redirect(url_for("app.index"))

    return render_template("auth/login.html", form=form)

@auth_module.route("/logout", methods=["GET", "POST"])
def logout():
    session.pop("username", None)
    session.clear()
    flash("既にログアウト済みです。", "info")
    return redirect(url_for("app.index"))

flaskdb/controller/views.py
from flask import Blueprint, request, session, render_template, redirect, flash, url_for

from flaskdb import apps, db, da
from flaskdb.model.userModel import User

from flaskdb.service.filesService import insert_files, select_all_files

app = Blueprint("app", __name__)


@app.route("/", methods=["GET", "POST"])
def index():
    if not "username" in session:
        flash("もう一度ログインしてください。", "danger")
        return redirect(url_for("auth.login"))

    memo_list = select_all_files()
    memo_md = []
    for num in range(len(memo_list)):
        if session['username'] == memo_list[num].user_name:
            memo_md.append(memo_list[num])
    return render_template("index.html", mdfiles = memo_md)


# This is a very danger method
@app.route("/receive", methods=["GET", "POST"])
def receive():
    if request.method == "GET":
        username = request.args.get("username")
        password = request.args.get("password")
    else:
        username = request.form["username"]
        password = request.form["password"]

    return render_template("receive.html", username=username, password=password)


@app.route("/initdb", methods=["GET", "POST"])
def initdb():
    db.drop_all()
    db.create_all()
    
    admin = User(username="admin", password="password")
    user = User(username="user", password="password")
    db.session.add(admin)
    db.session.add(user)
    db.session.commit()
    return "initidb() method was executed. "

flaskdb/templates/additem.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Add Item</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Add Item</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.additem') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="itemname">{{ form.itemname.label }}</label>
      {{ form.itemname(type="text", id="itemname", class="form-control", placeholder="Enter item name") }}
    </div>
    <div class="form-group">
      <label for="price">{{ form.price.label }}</label>
      {{ form.price(type="text", id="price", class="form-control", placeholder="Enter price") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
  {% if itemlist %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">User ID</th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    {% for item in itemlist %}
        <tr>
          <th scope="row">{{ item.id }}</th>
          <td>{{ item.user_id }}</td>
          <td>{{ item.itemname }}</td>
          <td>{{ item.price }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/templates/index.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Index</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse"> 
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Index</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  {% if "username" in session %}
  <p>Welcome, {{ session["username"] }}!</p>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/templates/login.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Index</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Login</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.login') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="username">{{ form.username.label }}</label>
      {{ form.username(type="text", id="username", class="form-control", placeholder="Enter your username") }}
    </div>
    <div class="form-group">
      <label for="password">{{ form.password.label }}</label>
      {{ form.password(type="password", id="password", class="form-control", placeholder="Enter your password") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/templates/logout.html
{% extends "bootstrap/base.html" %}

{% block head %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>flaskdb | Index</title>
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/flaskdb.css" rel="stylesheet">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Logout</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <p>Are you sure you want to log out?</p>
  <form action="{{ url_for('app.logout') }}" method="POST" novalidate>
    {{ form.csrf_token }}
    {{ form.cencel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/templates/nativesql.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Add Item</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Add Item</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.nativesql') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="itemname">{{ form.itemname.label }}</label>
      {{ form.itemname(type="text", id="itemname", class="form-control", placeholder="Enter item name") }}
    </div>
    <div class="form-group">
      <label for="price">{{ form.price.label }}</label>
      {{ form.price(type="text", id="price", class="form-control", placeholder="Enter price") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
  {% if itemlist %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">User ID</th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    {% for item in itemlist %}
        <tr>
          <th scope="row">{{ item.id }}</th>
          <td>{{ item.user_id }}</td>
          <td>{{ item.itemname }}</td>
          <td>{{ item.price }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}

flaskdb/templates/search.html
{% extends "bootstrap/base.html" %}

{% block head %}
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>flaskdb | Search Item</title>
  <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/css/flaskdb.css" rel="stylesheet">
  <!-- A Sample Web-DB Application for DB-DESIGN lecture -->
  <!-- Copyright (C) 2022 Yasuhiro Hayashi -->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('app.index') }}">flaskdb</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not "username" in session %}
        <li><a href="{{ url_for('app.login') }}">Login</a></li>
        {% else %}
        <li><a href="{{ url_for('app.additem') }}">Add Item</a></li>
        <li><a href="{{ url_for('app.searchitem') }}">Search Item</a></li>
        <li><a href="{{ url_for('app.logout') }}">Logout</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="page-header"><h1>Search Item</h1></div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}"> {{ message|capitalize }} </div>
      {% endfor %}
    {% endif %}
  {% endwith %}
  {% if form %}
    {% for field in form.errors %}
      {% for error in form.errors[field] %}
        <div class="alert alert-danger">{{ error }}</div>
      {% endfor %}
    {% endfor %}
  {% endif %}
  <form action="{{ url_for('app.searchitem') }}" method="POST" novalidate class="mb-10">
    <div class="form-group">
      <label for="itemname">{{ form.itemname.label }}</label>
      {{ form.itemname(type="text", id="itemname", class="form-control", placeholder="Enter keyword") }}
    </div>
    {{ form.csrf_token }}
    {{ form.cancel(class="btn") }}
    {{ form.submit(class="btn btn-primary") }}
  </form>
  {% if itemlist %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">User ID</th>
        <th scope="col">Item Name</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
    {% for item in itemlist %}
        <tr>
          <th scope="row">{{ item.id }}</th>
          <td>{{ item.user_id }}</td>
          <td>{{ item.itemname }}</td>
          <td>{{ item.price }}</td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ bootstrap_find_resource('jquery.js', cdn='jquery') }}"></script>
<script src="{{ bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap') }}"></script>
<script src="/static/js/flaskdb.js"></script>
{% endblock %}